# -*- coding: utf-8 -*-
"""
Localized demo content.

Real user data is shown exactly as entered. But the *seeded showcase* data must
read naturally in whatever UI language the viewer picks - otherwise a Greek or
Romanian visitor sees English sample text, which looks unprofessional.

So descriptive demo values are stored as tokens ("§key") and resolved here per
language. Proper nouns (company / people names) and pure codes, dates and
amounts (PO-2241, #4471, EUR 12,400, 2026-07-05) stay literal - the only mixing
that is genuinely unavoidable.
"""

LANGS = ("en", "bg", "de", "ro", "el", "tr", "it", "ru", "es", "fr", "pl", "uk", "pt")

TOKENS = {
    # ---- workspace names ---------------------------------------------------
    "ws_supply": {"en": "Key supplies 2026", "bg": "Ключови доставки 2026", "de": "Wichtige Lieferungen 2026", "ro": "Aprovizionări cheie 2026", "el": "Βασικές προμήθειες 2026", "tr": "Temel tedarikler 2026", "it": "Forniture chiave 2026", "ru": "Ключевые поставки 2026", "es": "Suministros clave 2026", "fr": "Livraisons clés 2026", "pl": "Kluczowe dostawy 2026", "uk": "Ключові постачання 2026", "pt": "Fornecimentos-chave 2026"},
    "ws_fulfil": {"en": "Online order fulfilment", "bg": "Изпълнение на онлайн поръчки", "de": "Online-Auftragsabwicklung", "ro": "Onorarea comenzilor online", "el": "Εκτέλεση online παραγγελιών", "tr": "Çevrimiçi sipariş karşılama", "it": "Evasione ordini online", "ru": "Выполнение онлайн-заказов", "es": "Fulfillment de pedidos online", "fr": "Exécution des commandes en ligne", "pl": "Realizacja zamówień online", "uk": "Виконання онлайн-замовлень", "pt": "Fulfillment de encomendas online"},
    "ws_build": {"en": "Store refurbishment", "bg": "Ремонт на магазини", "de": "Ladenrenovierung", "ro": "Renovarea magazinelor", "el": "Ανακαίνιση καταστημάτων", "tr": "Mağaza yenileme", "it": "Ristrutturazione negozi", "ru": "Ремонт магазинов", "es": "Reforma de tiendas", "fr": "Rénovation de magasins", "pl": "Remont sklepów", "uk": "Ремонт магазинів", "pt": "Remodelação de lojas"},

    # ---- order titles ------------------------------------------------------
    "o_packaging": {"en": "Packaging - quarterly", "bg": "Опаковки - тримесечно", "de": "Verpackung - vierteljährlich", "ro": "Ambalaje - trimestrial", "el": "Συσκευασία - τριμηνιαία", "tr": "Ambalaj - üç aylık", "it": "Imballaggi - trimestrale", "ru": "Упаковка - ежеквартально", "es": "Embalaje - trimestral", "fr": "Emballages - trimestriel", "pl": "Opakowania - kwartalnie", "uk": "Пакування - щоквартально", "pt": "Embalagens - trimestral"},
    "o_pallets": {"en": "EUR pallets - 200 pcs", "bg": "EUR палети - 200 бр", "de": "EUR-Paletten - 200 Stk", "ro": "Paleți EUR - 200 buc", "el": "Παλέτες EUR - 200 τεμ", "tr": "EUR palet - 200 adet", "it": "Pallet EUR - 200 pz", "ru": "EUR-паллеты - 200 шт", "es": "Palets EUR - 200 uds", "fr": "Palettes EUR - 200 pcs", "pl": "Palety EUR - 200 szt", "uk": "Палети EUR - 200 шт", "pt": "Paletes EUR - 200 un"},
    "o_batch1": {"en": "Weekly batch", "bg": "Седмична партида", "de": "Wöchentliche Charge", "ro": "Lot săptămânal", "el": "Εβδομαδιαία παρτίδα", "tr": "Haftalık parti", "it": "Lotto settimanale", "ru": "Недельная партия", "es": "Lote semanal", "fr": "Lot hebdomadaire", "pl": "Partia tygodniowa", "uk": "Тижнева партія", "pt": "Lote semanal"},
    "o_returns": {"en": "Returns - week 26", "bg": "Връщания - седмица 26", "de": "Retouren - Woche 26", "ro": "Retururi - săptămâna 26", "el": "Επιστροφές - εβδομάδα 26", "tr": "İadeler - hafta 26", "it": "Resi - settimana 26", "ru": "Возвраты - неделя 26", "es": "Devoluciones - semana 26", "fr": "Retours - semaine 26", "pl": "Zwroty - tydzień 26", "uk": "Повернення - тиждень 26", "pt": "Devoluções - semana 26"},
    "o_counter": {"en": "Counter & lighting", "bg": "Щанд и осветление", "de": "Theke & Beleuchtung", "ro": "Tejghea și iluminat", "el": "Πάγκος & φωτισμός", "tr": "Tezgah ve aydınlatma", "it": "Bancone e illuminazione", "ru": "Стойка и освещение", "es": "Mostrador e iluminación", "fr": "Comptoir et éclairage", "pl": "Lada i oświetlenie", "uk": "Стійка та освітлення", "pt": "Balcão e iluminação"},
    # The two records that ran to completion. A demo where nothing ever
    # finishes leaves the analytics screen with no cycle time to report.
    "o_shelving": {"en": "Shelving - 6 stores", "bg": "Стелажи - 6 магазина", "de": "Regale - 6 Filialen", "ro": "Rafturi - 6 magazine", "el": "Ράφια - 6 καταστήματα", "tr": "Raflar - 6 mağaza", "it": "Scaffalature - 6 negozi", "ru": "Стеллажи - 6 магазинов", "es": "Estanterías - 6 tiendas", "fr": "Rayonnages - 6 magasins", "pl": "Regały - 6 sklepów", "uk": "Стелажі - 6 магазинів", "pt": "Estanteria - 6 lojas"},
    "o_batch_w22": {"en": "Weekly batch - week 22", "bg": "Седмична партида - седмица 22", "de": "Wöchentliche Charge - Woche 22", "ro": "Lot săptămânal - săptămâna 22", "el": "Εβδομαδιαία παρτίδα - εβδομάδα 22", "tr": "Haftalık parti - hafta 22", "it": "Lotto settimanale - settimana 22", "ru": "Недельная партия - неделя 22", "es": "Lote semanal - semana 22", "fr": "Lot hebdomadaire - semaine 22", "pl": "Partia tygodniowa - tydzień 22", "uk": "Тижнева партія - тиждень 22", "pt": "Lote semanal - semana 22"},
    "o_electrical": {"en": "Electrical works", "bg": "Електро работи", "de": "Elektroarbeiten", "ro": "Lucrări electrice", "el": "Ηλεκτρολογικές εργασίες", "tr": "Elektrik işleri", "it": "Lavori elettrici", "ru": "Электромонтажные работы", "es": "Trabajos eléctricos", "fr": "Travaux électriques", "pl": "Prace elektryczne", "uk": "Електромонтажні роботи", "pt": "Trabalhos elétricos"},

    # ---- field values ------------------------------------------------------
    "f_boxes": {"en": "Cardboard boxes", "bg": "Картонени кутии", "de": "Kartons", "ro": "Cutii de carton", "el": "Χάρτινα κουτιά", "tr": "Karton kutular", "it": "Scatole di cartone", "ru": "Картонные коробки", "es": "Cajas de cartón", "fr": "Cartons", "pl": "Kartony", "uk": "Картонні коробки", "pt": "Caixas de cartão"},
    "f_qty_boxes": {"en": "5,000 / month", "bg": "5000 / месец", "de": "5.000 / Monat", "ro": "5.000 / lună", "el": "5.000 / μήνα", "tr": "5.000 / ay", "it": "5.000 / mese", "ru": "5000 / месяц", "es": "5.000 / mes", "fr": "5 000 / mois", "pl": "5 000 / miesiąc", "uk": "5 000 / місяць", "pt": "5 000 / mês"},
    "f_pallets": {"en": "Standard EUR pallets", "bg": "Стандартни EUR палети", "de": "Standard-EUR-Paletten", "ro": "Paleți EUR standard", "el": "Τυπικές παλέτες EUR", "tr": "Standart EUR palet", "it": "Pallet EUR standard", "ru": "Стандартные EUR-паллеты", "es": "Palets EUR estándar", "fr": "Palettes EUR standard", "pl": "Standardowe palety EUR", "uk": "Стандартні палети EUR", "pt": "Paletes EUR padrão"},
    "f_qty_pallets": {"en": "200 pcs", "bg": "200 бр", "de": "200 Stk", "ro": "200 buc", "el": "200 τεμ", "tr": "200 adet", "it": "200 pz", "ru": "200 шт", "es": "200 uds", "fr": "200 pcs", "pl": "200 szt", "uk": "200 шт", "pt": "200 un"},
    "f_shelving": {"en": "Steel shelving, 2.2 m", "bg": "Метални стелажи, 2,2 m", "de": "Stahlregale, 2,2 m", "ro": "Rafturi metalice, 2,2 m", "el": "Μεταλλικά ράφια, 2,2 m", "tr": "Çelik raf, 2,2 m", "it": "Scaffali in acciaio, 2,2 m", "ru": "Стальные стеллажи, 2,2 м", "es": "Estanterías de acero, 2,2 m", "fr": "Rayonnages en acier, 2,2 m", "pl": "Regały stalowe, 2,2 m", "uk": "Сталеві стелажі, 2,2 м", "pt": "Estantes de aço, 2,2 m"},
    "f_qty_shelving": {"en": "180 running metres", "bg": "180 линейни метра", "de": "180 laufende Meter", "ro": "180 metri liniari", "el": "180 τρέχοντα μέτρα", "tr": "180 metretül", "it": "180 metri lineari", "ru": "180 погонных метров", "es": "180 metros lineales", "fr": "180 mètres linéaires", "pl": "180 metrów bieżących", "uk": "180 погонних метрів", "pt": "180 metros lineares"},
    "f_dest_eu": {"en": "Courier to customers (EU)", "bg": "Куриер до клиенти (ЕС)", "de": "Kurier an Kunden (EU)", "ro": "Curier către clienți (UE)", "el": "Κούριερ σε πελάτες (ΕΕ)", "tr": "Müşterilere kurye (AB)", "it": "Corriere ai clienti (UE)", "ru": "Курьер клиентам (ЕС)", "es": "Mensajería a clientes (UE)", "fr": "Coursier vers les clients (UE)", "pl": "Kurier do klientów (UE)", "uk": "Кур'єр до клієнтів (ЄС)", "pt": "Transportadora para clientes (UE)"},
    "f_damaged": {"en": "5 damaged in transit", "bg": "5 повредени при транспорт", "de": "5 beim Transport beschädigt", "ro": "5 deteriorate în tranzit", "el": "5 κατεστραμμένα στη μεταφορά", "tr": "Nakliyede 5 hasarlı", "it": "5 danneggiati in transito", "ru": "5 повреждены при перевозке", "es": "5 dañados en tránsito", "fr": "5 endommagés en transit", "pl": "5 uszkodzonych w transporcie", "uk": "5 пошкоджено під час перевезення", "pt": "5 danificados em trânsito"},
    "f_counter": {"en": "Counter build + LED lighting", "bg": "Изграждане на щанд + LED осветление", "de": "Thekenbau + LED-Beleuchtung", "ro": "Construcție tejghea + iluminat LED", "el": "Κατασκευή πάγκου + φωτισμός LED", "tr": "Tezgah yapımı + LED aydınlatma", "it": "Costruzione bancone + illuminazione LED", "ru": "Сборка стойки + LED-освещение", "es": "Construcción de mostrador + iluminación LED", "fr": "Construction du comptoir + éclairage LED", "pl": "Budowa lady + oświetlenie LED", "uk": "Збірка стійки + LED-освітлення", "pt": "Construção de balcão + iluminação LED"},
    "f_loc_mall": {"en": "Mall A, unit 114", "bg": "Мол A, обект 114", "de": "Mall A, Einheit 114", "ro": "Mall A, unitatea 114", "el": "Mall A, κατάστημα 114", "tr": "AVM A, birim 114", "it": "Mall A, unità 114", "ru": "ТЦ A, помещение 114", "es": "Centro comercial A, local 114", "fr": "Centre commercial A, local 114", "pl": "Galeria A, lokal 114", "uk": "ТЦ A, приміщення 114", "pt": "Centro comercial A, loja 114"},
    "f_electrical": {"en": "Switchboard replacement + wiring", "bg": "Подмяна на ел. табло + окабеляване", "de": "Schalttafel-Austausch + Verkabelung", "ro": "Înlocuire tablou + cablare", "el": "Αντικατάσταση πίνακα + καλωδίωση", "tr": "Pano değişimi + kablolama", "it": "Sostituzione quadro + cablaggio", "ru": "Замена щита + проводка", "es": "Sustitución de cuadro + cableado", "fr": "Remplacement du tableau + câblage", "pl": "Wymiana rozdzielnicy + okablowanie", "uk": "Заміна щита + прокладання кабелю", "pt": "Substituição do quadro + cablagem"},
    "f_loc_store_b": {"en": "Store B, High St.", "bg": "Магазин B, ул. Главна", "de": "Filiale B, Hauptstraße", "ro": "Magazin B, str. Principală", "el": "Κατάστημα B, οδός Κεντρική", "tr": "Mağaza B, Ana Cad.", "it": "Negozio B, Via Principale", "ru": "Магазин B, Главная ул.", "es": "Tienda B, calle Mayor", "fr": "Magasin B, rue Principale", "pl": "Sklep B, ul. Główna", "uk": "Магазин B, вул. Головна", "pt": "Loja B, Rua Principal"},
    # The specification field was left empty and the order screen showed a bare
    # dash where a buyer looks for the substance of the job.
    "f_spec_electrical": {"en": "Three-phase board, 63 A main breaker, 12 circuits, RCD per group. Cable NYM 3x2.5 in trunking, existing runs kept where sound. Measurement protocol on completion.", "bg": "Трифазно табло, главен прекъсвач 63 A, 12 кръга, дефектнотокова защита по групи. Кабел NYM 3x2.5 в кабелен канал, съществуващите трасета се запазват, където са годни. Протокол от измервания при приключване.", "de": "Dreiphasige Verteilung, Hauptschalter 63 A, 12 Stromkreise, FI-Schutz je Gruppe. Kabel NYM 3x2,5 im Kanal, vorhandene Trassen bleiben, soweit intakt. Messprotokoll bei Abnahme.", "ro": "Tablou trifazat, întrerupător general 63 A, 12 circuite, protecție diferențială pe grupe. Cablu NYM 3x2,5 în canal, traseele existente se păstrează unde sunt bune. Proces-verbal de măsurători la finalizare.", "el": "Τριφασικός πίνακας, γενικός διακόπτης 63 A, 12 κυκλώματα, ρελέ διαρροής ανά ομάδα. Καλώδιο NYM 3x2,5 σε κανάλι, οι υπάρχουσες οδεύσεις διατηρούνται όπου είναι καλές. Πρωτόκολλο μετρήσεων στην παράδοση.", "tr": "Üç fazlı pano, 63 A ana şalter, 12 devre, grup başına kaçak akım rölesi. Kanal içinde NYM 3x2,5 kablo, sağlam olan mevcut güzergâhlar korunur. Teslimde ölçüm tutanağı.", "it": "Quadro trifase, interruttore generale 63 A, 12 circuiti, differenziale per gruppo. Cavo NYM 3x2,5 in canalina, i percorsi esistenti restano dove sono integri. Verbale di misura alla consegna.", "ru": "Трёхфазный щит, вводной автомат 63 A, 12 групп, УЗО на группу. Кабель NYM 3x2,5 в кабель-канале, существующие трассы сохраняются там, где пригодны. Протокол измерений при сдаче.", "es": "Cuadro trifásico, interruptor general de 63 A, 12 circuitos, diferencial por grupo. Cable NYM 3x2,5 en canaleta, se conservan los trazados existentes en buen estado. Acta de mediciones a la entrega.", "fr": "Tableau triphasé, disjoncteur général 63 A, 12 circuits, différentiel par groupe. Câble NYM 3x2,5 en goulotte, tracés existants conservés lorsqu'ils sont sains. Procès-verbal de mesures à la réception.", "pl": "Rozdzielnica trójfazowa, wyłącznik główny 63 A, 12 obwodów, różnicówka na grupę. Kabel NYM 3x2,5 w korycie, istniejące trasy zostają tam, gdzie są sprawne. Protokół pomiarów przy odbiorze.", "uk": "Трифазний щит, ввідний автомат 63 A, 12 груп, ПЗВ на групу. Кабель NYM 3x2,5 у кабель-каналі, наявні траси зберігаються там, де придатні. Протокол вимірювань під час здавання.", "pt": "Quadro trifásico, disjuntor geral de 63 A, 12 circuitos, diferencial por grupo. Cabo NYM 3x2,5 em calha, os traçados existentes mantêm-se onde estejam sãos. Auto de medições na entrega."},

    # ---- term values -------------------------------------------------------
    "t_price_unit": {"en": "€0.39 / unit", "bg": "0,39 € / бр", "de": "0,39 € / Stück", "ro": "1,95 lei / buc", "el": "0,39 € / τεμ", "tr": "14 ₺ / adet", "it": "0,39 € / pz", "ru": "39 ₽ / шт", "es": "0,39 € / ud", "fr": "0,39 € / pc", "pl": "0,39 € / szt", "uk": "0,39 € / шт", "pt": "0,39 € / un"},
    "t_scope_dc": {"en": "Delivery to central warehouse, unloading included", "bg": "Доставка до централен склад, разтоварване включено", "de": "Lieferung ans Zentrallager, Entladung inklusive", "ro": "Livrare la depozitul central, descărcare inclusă", "el": "Παράδοση στην κεντρική αποθήκη, εκφόρτωση περιλαμβάνεται", "tr": "Merkez depoya teslimat, boşaltma dahil", "it": "Consegna al magazzino centrale, scarico incluso", "ru": "Доставка на центральный склад, разгрузка включена", "es": "Entrega al almacén central, descarga incluida", "fr": "Livraison à l'entrepôt central, déchargement inclus", "pl": "Dostawa do magazynu centralnego, rozładunek w cenie", "uk": "Доставка на центральний склад, розвантаження включено", "pt": "Entrega no armazém central, descarga incluída"},
    "t_price_pallet": {"en": "€14.50 / pc", "bg": "14,50 € / бр", "de": "14,50 € / Stück", "ro": "72 lei / buc", "el": "14,50 € / τεμ", "tr": "510 ₺ / adet", "it": "14,50 € / pz", "ru": "1 450 ₽ / шт", "es": "14,50 € / ud", "fr": "14,50 € / pc", "pl": "14,50 € / szt", "uk": "14,50 € / шт", "pt": "14,50 € / un"},
    "t_price_order": {"en": "€1.10 / order", "bg": "1,10 € / поръчка", "de": "1,10 € / Auftrag", "ro": "5,50 lei / comandă", "el": "1,10 € / παραγγελία", "tr": "39 ₺ / sipariş", "it": "1,10 € / ordine", "ru": "110 ₽ / заказ", "es": "1,10 € / pedido", "fr": "1,10 € / commande", "pl": "1,10 € / zamówienie", "uk": "1,10 € / замовлення", "pt": "1,10 € / encomenda"},
    "t_price_counter": {"en": "€12,400", "bg": "12 400 €", "de": "12.400 €", "ro": "62.000 lei", "el": "12.400 €", "tr": "434.000 ₺", "it": "12.400 €", "ru": "1 240 000 ₽", "es": "12.400 €", "fr": "12 400 €", "pl": "12 400 €", "uk": "12 400 €", "pt": "12 400 €"},
    "t_price_elec": {"en": "€8,900", "bg": "8 900 €", "de": "8.900 €", "ro": "44.500 lei", "el": "8.900 €", "tr": "311.000 ₺", "it": "8.900 €", "ru": "890 000 ₽", "es": "8.900 €", "fr": "8 900 €", "pl": "8 900 €", "uk": "8 900 €", "pt": "8 900 €"},
    "t_sla_24": {"en": "Dispatch within 24h", "bg": "Изпращане до 24ч", "de": "Versand innerhalb 24 Std", "ro": "Expediere în 24h", "el": "Αποστολή εντός 24ω", "tr": "24 saat içinde gönderim", "it": "Spedizione entro 24h", "ru": "Отправка в течение 24ч", "es": "Envío en 24h", "fr": "Expédition sous 24h", "pl": "Wysyłka w 24h", "uk": "Відправлення протягом 24 год", "pt": "Expedição em 24h"},
    "t_proc_48": {"en": "Process within 48h", "bg": "Обработка до 48ч", "de": "Bearbeitung innerhalb 48 Std", "ro": "Procesare în 48h", "el": "Επεξεργασία εντός 48ω", "tr": "48 saat içinde işlem", "it": "Elaborazione entro 48h", "ru": "Обработка в течение 48ч", "es": "Procesar en 48h", "fr": "Traitement sous 48h", "pl": "Realizacja w 48h", "uk": "Обробка протягом 48 год", "pt": "Processamento em 48h"},
    "t_pay_5050": {"en": "50% deposit, 50% on sign-off", "bg": "50% аванс, 50% при приемане", "de": "50% Anzahlung, 50% bei Abnahme", "ro": "50% avans, 50% la recepție", "el": "50% προκαταβολή, 50% στην παραλαβή", "tr": "%50 peşin, %50 kabulde", "it": "50% acconto, 50% al collaudo", "ru": "50% аванс, 50% при приёмке", "es": "50% de anticipo, 50% a la aceptación", "fr": "50% d'acompte, 50% à la réception", "pl": "50% zaliczki, 50% przy odbiorze", "uk": "50% аванс, 50% при прийманні", "pt": "50% de sinal, 50% na receção"},
    "t_scope_full": {"en": "Materials, labour and waste removal", "bg": "Материали, труд и извозване на отпадъци", "de": "Material, Arbeit und Entsorgung", "ro": "Materiale, manoperă și evacuarea deșeurilor", "el": "Υλικά, εργασία και απομάκρυνση απορριμμάτων", "tr": "Malzeme, işçilik ve atık kaldırma", "it": "Materiali, manodopera e rimozione rifiuti", "ru": "Материалы, работа и вывоз отходов", "es": "Materiales, mano de obra y retirada de residuos", "fr": "Matériaux, main-d'œuvre et évacuation des déchets", "pl": "Materiały, robocizna i wywóz odpadów", "uk": "Матеріали, робота та вивезення відходів", "pt": "Materiais, mão de obra e remoção de resíduos"},

    # ---- comments ----------------------------------------------------------
    "c_friday": {"en": "Can the first batch arrive by Friday?", "bg": "Може ли първата партида до петък?", "de": "Kann die erste Charge bis Freitag kommen?", "ro": "Poate ajunge primul lot până vineri?", "el": "Μπορεί η πρώτη παρτίδα ως την Παρασκευή;", "tr": "İlk parti cumaya kadar gelebilir mi?", "it": "Il primo lotto può arrivare entro venerdì?", "ru": "Первая партия успеет к пятнице?", "es": "¿Puede llegar el primer lote antes del viernes?", "fr": "Le premier lot peut-il arriver d'ici vendredi ?", "pl": "Czy pierwsza partia dotrze do piątku?", "uk": "Чи встигне перша партія до п'ятниці?", "pt": "O primeiro lote pode chegar até sexta-feira?"},
    "c_gradea": {"en": "Price is for new, grade A pallets.", "bg": "Цената е за нови палети, клас А.", "de": "Preis gilt für neue Paletten, Klasse A.", "ro": "Prețul este pentru paleți noi, clasa A.", "el": "Η τιμή είναι για νέες παλέτες, κατηγορία Α.", "tr": "Fiyat yeni, A sınıfı paletler içindir.", "it": "Il prezzo è per pallet nuovi, classe A.", "ru": "Цена за новые паллеты, класс А.", "es": "El precio es para palets nuevos, clase A.", "fr": "Le prix concerne des palettes neuves, classe A.", "pl": "Cena dotyczy nowych palet, klasa A.", "uk": "Ціна за нові палети, клас А.", "pt": "O preço é para paletes novas, classe A."},
    "c_received_ok": {"en": "All six stores received and checked. Closing this one.", "bg": "И шестте магазина приеха и провериха доставката. Приключваме поръчката.", "de": "Alle sechs Filialen haben angenommen und geprüft. Wir schließen den Auftrag.", "ro": "Toate cele șase magazine au recepționat și verificat. Închidem comanda.", "el": "Και τα έξι καταστήματα παρέλαβαν και έλεγξαν. Κλείνουμε την παραγγελία.", "tr": "Altı mağaza da teslim aldı ve kontrol etti. Siparişi kapatıyoruz.", "it": "Tutti e sei i negozi hanno ricevuto e verificato. Chiudiamo l'ordine.", "ru": "Все шесть магазинов приняли и проверили. Закрываем заказ.", "es": "Las seis tiendas han recibido y comprobado. Cerramos el pedido.", "fr": "Les six magasins ont réceptionné et vérifié. Nous clôturons la commande.", "pl": "Wszystkie sześć sklepów odebrało i sprawdziło. Zamykamy zamówienie.", "uk": "Усі шість магазинів прийняли та перевірили. Закриваємо замовлення.", "pt": "As seis lojas receberam e verificaram. Encerramos a encomenda."},
    "c_delivered_ok": {"en": "All parcels delivered, no claims. Closed.", "bg": "Всички пратки доставени, без рекламации. Приключено.", "de": "Alle Sendungen zugestellt, keine Reklamationen. Abgeschlossen.", "ro": "Toate coletele livrate, fără reclamații. Închis.", "el": "Όλα τα δέματα παραδόθηκαν, χωρίς παράπονα. Έκλεισε.", "tr": "Tüm gönderiler teslim edildi, şikâyet yok. Kapatıldı.", "it": "Tutti i colli consegnati, nessun reclamo. Chiuso.", "ru": "Все посылки доставлены, претензий нет. Закрыто.", "es": "Todos los paquetes entregados, sin reclamaciones. Cerrado.", "fr": "Tous les colis livrés, aucune réclamation. Clôturé.", "pl": "Wszystkie paczki dostarczone, bez reklamacji. Zamknięte.", "uk": "Усі посилки доставлено, претензій немає. Закрито.", "pt": "Todas as encomendas entregues, sem reclamações. Encerrado."},
    "c_sla_ok": {"en": "All shipped within SLA.", "bg": "Всичко изпратено в срок (SLA).", "de": "Alles innerhalb des SLA versandt.", "ro": "Totul expediat în SLA.", "el": "Όλα στάλθηκαν εντός SLA.", "tr": "Hepsi SLA içinde gönderildi.", "it": "Tutto spedito entro lo SLA.", "ru": "Всё отправлено в рамках SLA.", "es": "Todo enviado dentro del SLA.", "fr": "Tout expédié dans les délais (SLA).", "pl": "Wszystko wysłane w ramach SLA.", "uk": "Усе відправлено в межах SLA.", "pt": "Tudo expedido dentro do SLA."},
    "c_damaged_q": {"en": "5 items arrived damaged, photos attached. How do we proceed?", "bg": "5 артикула пристигнаха повредени, прилагам снимки. Как процедираме?", "de": "5 Artikel kamen beschädigt an, Fotos anbei. Wie gehen wir vor?", "ro": "5 articole au sosit deteriorate, foto atașate. Cum procedăm?", "el": "5 είδη έφτασαν κατεστραμμένα, φωτογραφίες συνημμένες. Πώς προχωράμε;", "tr": "5 ürün hasarlı geldi, fotoğraflar ekte. Nasıl ilerleyelim?", "it": "5 articoli arrivati danneggiati, foto allegate. Come procediamo?", "ru": "5 позиций пришли повреждёнными, фото приложены. Как поступим?", "es": "5 artículos llegaron dañados, fotos adjuntas. ¿Cómo procedemos?", "fr": "5 articles arrivés endommagés, photos jointes. Comment procède-t-on ?", "pl": "5 sztuk dotarło uszkodzonych, zdjęcia w załączniku. Jak postępujemy?", "uk": "5 позицій прибули пошкодженими, фото додано. Як діємо?", "pt": "5 artigos chegaram danificados, fotos em anexo. Como procedemos?"},
    "c_scrap": {"en": "Scrap the damaged ones, restock the rest.", "bg": "Бракувайте повредените, останалите върнете в наличност.", "de": "Beschädigte entsorgen, Rest wieder einlagern.", "ro": "Casează cele deteriorate, restul repune în stoc.", "el": "Πετάξτε τα κατεστραμμένα, τα υπόλοιπα επιστροφή σε απόθεμα.", "tr": "Hasarlıları imha edin, kalanları stoğa alın.", "it": "Rottama i danneggiati, rimetti a stock il resto.", "ru": "Повреждённые в утиль, остальное верните на склад.", "es": "Desechad los dañados, reponed el resto.", "fr": "Mettez au rebut les endommagés, remettez le reste en stock.", "pl": "Uszkodzone na złom, resztę z powrotem na stan.", "uk": "Пошкоджені спишіть, решту поверніть на склад.", "pt": "Abatam os danificados, reponham o resto em stock."},
    "c_night": {"en": "Site access after 21:00.", "bg": "Достъп до обекта след 21:00.", "de": "Baustellenzugang ab 21:00.", "ro": "Acces pe șantier după 21:00.", "el": "Πρόσβαση στο εργοτάξιο μετά τις 21:00.", "tr": "Şantiye girişi 21:00'den sonra.", "it": "Accesso al cantiere dopo le 21:00.", "ru": "Доступ на объект после 21:00.", "es": "Acceso a la obra después de las 21:00.", "fr": "Accès au chantier après 21h00.", "pl": "Dostęp do obiektu po 21:00.", "uk": "Доступ до об'єкта після 21:00.", "pt": "Acesso à obra após as 21:00."},
    "c_cert": {"en": "Price includes certification by a licensed electrician.", "bg": "Цената включва сертификат от лицензиран електротехник.", "de": "Preis inkl. Zertifizierung durch einen zugelassenen Elektriker.", "ro": "Prețul include certificarea de un electrician autorizat.", "el": "Η τιμή περιλαμβάνει πιστοποίηση από αδειούχο ηλεκτρολόγο.", "tr": "Fiyata lisanslı elektrikçi sertifikası dahildir.", "it": "Il prezzo include la certificazione di un elettricista abilitato.", "ru": "Цена включает сертификацию лицензированным электриком.", "es": "El precio incluye la certificación de un electricista autorizado.", "fr": "Le prix inclut la certification par un électricien agréé.", "pl": "Cena obejmuje certyfikację przez uprawnionego elektryka.", "uk": "Ціна включає сертифікацію ліцензованим електриком.", "pt": "O preço inclui a certificação por um eletricista credenciado."},

    # ---- store demo (products / customers) ---------------------------------
    "p_cable": {"en": "USB-C cable 2m", "bg": "USB-C кабел 2m", "de": "USB-C-Kabel 2m", "ro": "Cablu USB-C 2m", "el": "Καλώδιο USB-C 2m", "tr": "USB-C kablo 2m", "it": "Cavo USB-C 2m", "ru": "USB-C кабель 2м", "es": "Cable USB-C 2m", "fr": "Câble USB-C 2m", "pl": "Kabel USB-C 2m", "uk": "Кабель USB-C 2м", "pt": "Cabo USB-C 2m"},
    "p_license": {"en": "Software license Pro", "bg": "Софтуерен лиценз Pro", "de": "Softwarelizenz Pro", "ro": "Licență software Pro", "el": "Άδεια λογισμικού Pro", "tr": "Yazılım lisansı Pro", "it": "Licenza software Pro", "ru": "Лицензия ПО Pro", "es": "Licencia de software Pro", "fr": "Licence logicielle Pro", "pl": "Licencja oprogramowania Pro", "uk": "Ліцензія ПЗ Pro", "pt": "Licença de software Pro"},
    "p_gamekey": {"en": "Game activation key", "bg": "Ключ за игра", "de": "Spiel-Aktivierungsschlüssel", "ro": "Cheie de activare joc", "el": "Κλειδί ενεργοποίησης παιχνιδιού", "tr": "Oyun etkinleştirme anahtarı", "it": "Chiave di attivazione gioco", "ru": "Ключ активации игры", "es": "Clave de activación de juego", "fr": "Clé d'activation de jeu", "pl": "Klucz aktywacyjny gry", "uk": "Ключ активації гри", "pt": "Chave de ativação de jogo"},
    "c_client_a": {"en": "Retail partner A", "bg": "Търговски партньор А", "de": "Händler A", "ro": "Partener retail A", "el": "Λιανικός συνεργάτης Α", "tr": "Perakende iş ortağı A", "it": "Partner retail A", "ru": "Розничный партнёр А", "es": "Socio minorista A", "fr": "Partenaire de détail A", "pl": "Partner detaliczny A", "uk": "Роздрібний партнер А", "pt": "Parceiro retalhista A"},
    "c_client_b": {"en": "Online buyer B", "bg": "Онлайн клиент Б", "de": "Online-Käufer B", "ro": "Cumpărător online B", "el": "Online αγοραστής Β", "tr": "Çevrimiçi alıcı B", "it": "Acquirente online B", "ru": "Онлайн-покупатель Б", "es": "Comprador online B", "fr": "Acheteur en ligne B", "pl": "Kupujący online B", "uk": "Онлайн-покупець Б", "pt": "Comprador online B"},

    # ---- workspace communication demo --------------------------------------
    "m_kickoff": {"en": "Welcome to our shared workspace. Let's keep all supply topics here.", "bg": "Добре дошли в общото ни пространство. Нека държим всички теми по доставките тук.", "de": "Willkommen in unserem gemeinsamen Bereich. Halten wir alle Lieferthemen hier fest.", "ro": "Bine ați venit în spațiul nostru comun. Să ținem aici toate subiectele de aprovizionare.", "el": "Καλώς ήρθατε στον κοινό μας χώρο. Ας κρατάμε εδώ όλα τα θέματα προμηθειών.", "tr": "Ortak alanımıza hoş geldiniz. Tüm tedarik konularını burada tutalım.", "it": "Benvenuti nel nostro spazio condiviso. Teniamo qui tutti i temi di fornitura.", "ru": "Добро пожаловать в наше общее пространство. Давайте держать все вопросы поставок здесь.", "es": "Bienvenidos a nuestro espacio compartido. Mantengamos aquí todos los temas de suministro.", "fr": "Bienvenue dans notre espace partagé. Gardons ici tous les sujets d'approvisionnement.", "pl": "Witamy w naszej wspólnej przestrzeni. Trzymajmy tu wszystkie tematy dostaw.", "uk": "Вітаємо в нашому спільному просторі. Тримаймо тут усі теми щодо постачання.", "pt": "Bem-vindos ao nosso espaço partilhado. Mantenhamos aqui todos os temas de fornecimento."},
    "m_reply": {"en": "Thank you! Works for us - our team will respond here within the day.", "bg": "Благодарим! Устройва ни - екипът ни ще отговаря тук в рамките на деня.", "de": "Danke! Passt für uns - unser Team antwortet hier innerhalb des Tages.", "ro": "Mulțumim! Ne convine - echipa noastră va răspunde aici în cursul zilei.", "el": "Ευχαριστούμε! Μας βολεύει - η ομάδα μας θα απαντά εδώ εντός της ημέρας.", "tr": "Teşekkürler! Bize uyar - ekibimiz gün içinde burada yanıt verecek.", "it": "Grazie! Per noi va bene - il nostro team risponderà qui in giornata.", "ru": "Спасибо! Нам подходит - наша команда будет отвечать здесь в течение дня.", "es": "¡Gracias! Nos viene bien - nuestro equipo responderá aquí durante el día.", "fr": "Merci ! Cela nous convient - notre équipe répondra ici dans la journée.", "pl": "Dziękujemy! Pasuje nam - nasz zespół odpowie tutaj w ciągu dnia.", "uk": "Дякуємо! Нам підходить - наша команда відповідатиме тут протягом дня.", "pt": "Obrigado! Serve-nos - a nossa equipa responderá aqui ao longo do dia."},
    "m_emg_note": {"en": "Dispatch reachable 08:00-20:00; after hours use WhatsApp.", "bg": "Диспечер на разположение 08:00-20:00; извън работно време през WhatsApp.", "de": "Disposition erreichbar 08:00-20:00; außerhalb über WhatsApp.", "ro": "Dispecerat disponibil 08:00-20:00; în afara programului pe WhatsApp.", "el": "Συντονιστής διαθέσιμος 08:00-20:00· εκτός ωραρίου μέσω WhatsApp.", "tr": "Sevkiyat 08:00-20:00 arası ulaşılabilir; mesai dışı WhatsApp.", "it": "Logistica reperibile 08:00-20:00; fuori orario su WhatsApp.", "ru": "Диспетчер на связи 08:00-20:00; в нерабочее время через WhatsApp.", "es": "Logística disponible 08:00-20:00; fuera de horario por WhatsApp.", "fr": "Logistique joignable 08:00-20:00 ; hors horaires via WhatsApp.", "pl": "Logistyka dostępna 08:00-20:00; poza godzinami przez WhatsApp.", "uk": "Диспетчер на зв'язку 08:00-20:00; поза робочим часом через WhatsApp.", "pt": "Logística disponível 08:00-20:00; fora de horas por WhatsApp."},
}


def translate(key, lang):
    row = TOKENS.get(key)
    if not row:
        return key
    return row.get(lang) or row.get("en") or key
