# -*- coding: utf-8 -*-
"""The privacy and question pages, kept beside public_text for readability.

Both are short for the same reason the terms are: a reader who cannot check a
claim against the software has not been told anything.
"""

PRIVACY = {
 "title": {
  "en": "Privacy", "bg": "Поверителност", "de": "Datenschutz", "ro": "Confidențialitate",
  "el": "Απόρρητο", "tr": "Gizlilik", "it": "Riservatezza", "ru": "Конфиденциальность",
  "es": "Privacidad", "fr": "Confidentialité", "pl": "Prywatność",
  "uk": "Конфіденційність", "pt": "Privacidade"},
 "lead": {
  "en": "What is kept, who sees it, and how to have your part removed.",
  "bg": "Какво се пази, кой го вижда и как вашата част отпада.",
  "de": "Was gespeichert wird, wer es sieht und wie Ihr Teil gelöscht wird.",
  "ro": "Ce se păstrează, cine vede și cum vă puteți șterge partea.",
  "el": "Τι κρατείται, ποιος το βλέπει και πώς διαγράφεται το δικό σας μέρος.",
  "tr": "Ne saklanıyor, kim görüyor ve sizin kısmınız nasıl siliniyor.",
  "it": "Che cosa viene conservato, chi lo vede e come far cancellare la sua parte.",
  "ru": "Что хранится, кто это видит и как удалить вашу часть.",
  "es": "Qué se guarda, quién lo ve y cómo eliminar su parte.",
  "fr": "Ce qui est conservé, qui le voit et comment faire supprimer votre part.",
  "pl": "Co jest przechowywane, kto to widzi i jak usunąć Państwa część.",
  "uk": "Що зберігається, хто це бачить і як видалити вашу частину.",
  "pt": "O que é guardado, quem o vê e como remover a sua parte."},
 "items": [
  ({"en": "What is stored", "bg": "Какво се съхранява", "de": "Was gespeichert wird",
    "ro": "Ce se stochează", "el": "Τι αποθηκεύεται", "tr": "Ne saklanır",
    "it": "Che cosa viene memorizzato", "ru": "Что хранится", "es": "Qué se almacena",
    "fr": "Ce qui est stocké", "pl": "Co jest przechowywane", "uk": "Що зберігається",
    "pt": "O que é armazenado"},
   {"en": "Your name, e-mail and telephone, and the records you take part in: orders, agreed terms, documents, files, and the log of who changed what and when.",
    "bg": "Вашето име, имейл и телефон, както и поръчките, по които участвате: договорени условия, документи, файлове и записът кой какво и кога е променил.",
    "de": "Ihr Name, Ihre E-Mail und Telefonnummer sowie die Vorgänge, an denen Sie beteiligt sind: Konditionen, Dokumente, Dateien und das Protokoll, wer wann was geändert hat.",
    "ro": "Numele, e-mailul și telefonul dvs., precum și comenzile la care participați: condiții convenite, documente, fișiere și jurnalul cine, ce și când a modificat.",
    "el": "Το όνομα, το e-mail και το τηλέφωνό σας, καθώς και οι παραγγελίες στις οποίες συμμετέχετε: όροι, έγγραφα, αρχεία και το ημερολόγιο του ποιος άλλαξε τι και πότε.",
    "tr": "Adınız, e-postanız ve telefonunuz ile katıldığınız kayıtlar: anlaşılan koşullar, belgeler, dosyalar ve kimin neyi ne zaman değiştirdiğinin kaydı.",
    "it": "Il suo nome, e-mail e telefono, e le pratiche a cui partecipa: condizioni concordate, documenti, file e il registro di chi ha cambiato che cosa e quando.",
    "ru": "Ваши имя, почта и телефон, а также записи, в которых вы участвуете: согласованные условия, документы, файлы и журнал того, кто что и когда изменил.",
    "es": "Su nombre, correo y teléfono, y los expedientes en los que participa: condiciones acordadas, documentos, archivos y el registro de quién cambió qué y cuándo.",
    "fr": "Vos nom, e-mail et téléphone, et les dossiers auxquels vous participez: conditions convenues, documents, fichiers et le journal de qui a modifié quoi et quand.",
    "pl": "Państwa imię, e-mail i telefon oraz zamówienia, w których Państwo uczestniczą: uzgodnione warunki, dokumenty, pliki i zapis, kto co i kiedy zmienił.",
    "uk": "Ваші ім'я, пошта й телефон, а також записи, у яких ви берете участь: погоджені умови, документи, файли та журнал того, хто що і коли змінив.",
    "pt": "O seu nome, e-mail e telefone, e os registos em que participa: condições acordadas, documentos, ficheiros e o registo de quem alterou o quê e quando."}),

  ({"en": "Who can see it", "bg": "Кой го вижда", "de": "Wer es sehen kann",
    "ro": "Cine poate vedea", "el": "Ποιος μπορεί να το δει", "tr": "Kim görebilir",
    "it": "Chi può vederlo", "ru": "Кто это видит", "es": "Quién puede verlo",
    "fr": "Qui peut le voir", "pl": "Kto może to zobaczyć", "uk": "Хто це бачить",
    "pt": "Quem o pode ver"},
   {"en": "Only the two companies party to a record, and the administrator of this installation. Your other counterparties are never listed to anyone, and no company learns which partner you have in common with another.",
    "bg": "Само двете фирми по дадена поръчка и администраторът на инсталацията. Останалите ви контрагенти не се показват на никого и никоя фирма не научава кой партньор имате общ с друга.",
    "de": "Nur die beiden Firmen eines Vorgangs und der Administrator dieser Installation. Ihre übrigen Geschäftspartner werden niemandem aufgelistet, und keine Firma erfährt, welchen Partner Sie mit einer anderen gemeinsam haben.",
    "ro": "Doar cele două firme dintr-o comandă și administratorul acestei instalări. Ceilalți parteneri ai dvs. nu sunt listați nimănui, iar nicio firmă nu află ce partener aveți în comun cu alta.",
    "el": "Μόνο οι δύο εταιρείες μιας παραγγελίας και ο διαχειριστής της εγκατάστασης. Οι υπόλοιποι αντισυμβαλλόμενοί σας δεν εμφανίζονται σε κανέναν, και καμία εταιρεία δεν μαθαίνει ποιον συνεργάτη έχετε κοινό με άλλη.",
    "tr": "Yalnızca bir kayda taraf iki şirket ve bu kurulumun yöneticisi. Diğer muhataplarınız kimseye listelenmez ve hiçbir şirket bir başkasıyla hangi ortağı paylaştığınızı öğrenmez.",
    "it": "Solo le due aziende parti di una pratica e l'amministratore di questa installazione. Le sue altre controparti non sono elencate a nessuno e nessuna azienda scopre quale partner ha in comune con un'altra.",
    "ru": "Только две компании по записи и администратор этой установки. Остальные ваши контрагенты никому не перечисляются, и ни одна компания не узнаёт, какой партнёр у вас общий с другой.",
    "es": "Solo las dos empresas parte de un expediente y el administrador de esta instalación. Sus demás contrapartes no se muestran a nadie y ninguna empresa averigua qué socio comparte con otra.",
    "fr": "Seules les deux entreprises parties à un dossier et l'administrateur de cette installation. Vos autres contreparties ne sont listées à personne, et aucune entreprise n'apprend quel partenaire vous avez en commun avec une autre.",
    "pl": "Tylko dwie firmy będące stronami zamówienia oraz administrator tej instalacji. Pozostali Państwa kontrahenci nie są nikomu wyliczani i żadna firma nie dowiaduje się, którego partnera mają Państwo wspólnego z inną.",
    "uk": "Лише дві компанії за записом і адміністратор цієї інсталяції. Решта ваших контрагентів нікому не перелічуються, і жодна компанія не дізнається, якого партнера ви маєте спільного з іншою.",
    "pt": "Apenas as duas empresas partes de um registo e o administrador desta instalação. As suas outras contrapartes não são listadas a ninguém e nenhuma empresa fica a saber que parceiro tem em comum com outra."}),

  ({"en": "Cookies", "bg": "Бисквитки", "de": "Cookies", "ro": "Cookie-uri",
    "el": "Cookies", "tr": "Çerezler", "it": "Cookie", "ru": "Cookie",
    "es": "Cookies", "fr": "Cookies", "pl": "Pliki cookie", "uk": "Cookie",
    "pt": "Cookies"},
   {"en": "Three: your session, your language and your theme. Each is needed for the site to work or is set by your own choice, none tracks you and none is shared. That is why there is no consent banner, and why one would be theatre.",
    "bg": "Три: вашата сесия, вашият език и вашата тема. Всяка е нужна за работата на сайта или е зададена по ваш избор, никоя не ви проследява и никоя не се споделя. Затова няма банер за съгласие, а и щеше да е театър.",
    "de": "Drei: Ihre Sitzung, Ihre Sprache und Ihr Erscheinungsbild. Jedes ist für den Betrieb nötig oder von Ihnen selbst gesetzt, keines verfolgt Sie, keines wird geteilt. Darum gibt es kein Einwilligungsbanner, und eines wäre Theater.",
    "ro": "Trei: sesiunea, limba și tema dvs. Fiecare este necesar funcționării sau este pus de dvs., niciunul nu vă urmărește și niciunul nu se împarte. De aceea nu există banner de consimțământ, iar unul ar fi teatru.",
    "el": "Τρία: η συνεδρία σας, η γλώσσα σας και το θέμα σας. Καθένα χρειάζεται για να δουλέψει ο ιστότοπος ή το ορίζετε εσείς, κανένα δεν σας παρακολουθεί και κανένα δεν μοιράζεται. Γι αυτό δεν υπάρχει μπάνερ συγκατάθεσης, και θα ήταν θέατρο.",
    "tr": "Üç tane: oturumunuz, diliniz ve temanız. Her biri sitenin çalışması için gerekli ya da sizin seçiminizle konur; hiçbiri sizi izlemez, hiçbiri paylaşılmaz. Bu yüzden onay bandı yok, olsaydı da tiyatro olurdu.",
    "it": "Tre: la sua sessione, la sua lingua e il suo tema. Ognuno serve al funzionamento o lo imposta lei, nessuno la traccia e nessuno viene condiviso. Per questo non c'è un banner di consenso, e sarebbe teatro.",
    "ru": "Три: ваша сессия, ваш язык и ваша тема. Каждая нужна для работы или задаётся вами, ни одна не отслеживает вас и ни одна не передаётся. Поэтому баннера согласия нет, а был бы он театром.",
    "es": "Tres: su sesión, su idioma y su tema. Cada una hace falta para que el sitio funcione o la fija usted, ninguna le rastrea y ninguna se comparte. Por eso no hay banner de consentimiento, y sería teatro.",
    "fr": "Trois: votre session, votre langue et votre thème. Chacun est nécessaire au fonctionnement ou fixé par vous, aucun ne vous suit et aucun n'est partagé. D'où l'absence de bandeau de consentement, qui ne serait que théâtre.",
    "pl": "Trzy: sesja, język i motyw. Każdy jest potrzebny do działania albo ustawiają go Państwo sami, żaden nie śledzi i żaden nie jest udostępniany. Dlatego nie ma banera zgody, a byłby teatrem.",
    "uk": "Три: ваша сесія, ваша мова і ваша тема. Кожен потрібен для роботи або задається вами, жоден не стежить за вами й жоден не передається. Тому банера згоди немає, а був би він театром.",
    "pt": "Três: a sua sessão, o seu idioma e o seu tema. Cada um é preciso para o site funcionar ou é definido por si, nenhum o segue e nenhum é partilhado. Por isso não há banner de consentimento, e seria teatro."}),

  ({"en": "Removing yourself", "bg": "Как отпадате", "de": "Sich löschen lassen",
    "ro": "Cum vă ștergeți", "el": "Διαγραφή σας", "tr": "Kendinizi silmek",
    "it": "Farsi cancellare", "ru": "Как удалиться", "es": "Cómo eliminarse",
    "fr": "Vous faire supprimer", "pl": "Usunięcie siebie", "uk": "Як видалитися",
    "pt": "Como se remover"},
   {"en": "On request your name, e-mail, telephone, signature and devices are deleted. What two companies agreed stays, because removing a person cannot undo an agreement, but your name is no longer on it.",
    "bg": "При поискване вашето име, имейл, телефон, подпис и устройства се изтриват. Договореното между двете фирми остава, защото заличаването на човек не отменя договорка, но вече без вашето име.",
    "de": "Auf Wunsch werden Ihr Name, E-Mail, Telefon, Unterschrift und Geräte gelöscht. Das zwischen zwei Firmen Vereinbarte bleibt, denn das Löschen einer Person hebt keine Vereinbarung auf, jedoch ohne Ihren Namen.",
    "ro": "La cerere, numele, e-mailul, telefonul, semnătura și dispozitivele dvs. se șterg. Ce au convenit două firme rămâne, fiindcă ștergerea unei persoane nu desface o înțelegere, însă fără numele dvs.",
    "el": "Κατόπιν αιτήματος διαγράφονται το όνομα, το e-mail, το τηλέφωνο, η υπογραφή και οι συσκευές σας. Ό,τι συμφώνησαν δύο εταιρείες μένει, γιατί η διαγραφή προσώπου δεν λύνει συμφωνία, αλλά χωρίς το όνομά σας.",
    "tr": "Talep üzerine adınız, e-postanız, telefonunuz, imzanız ve cihazlarınız silinir. İki şirketin anlaştığı şey kalır, çünkü bir kişiyi silmek anlaşmayı bozmaz, ama artık adınız olmadan.",
    "it": "Su richiesta nome, e-mail, telefono, firma e dispositivi vengono cancellati. Quanto concordato tra due aziende resta, perché cancellare una persona non scioglie un accordo, ma senza il suo nome.",
    "ru": "По запросу ваши имя, почта, телефон, подпись и устройства удаляются. Согласованное между двумя компаниями остаётся, потому что удаление человека не отменяет договорённость, но уже без вашего имени.",
    "es": "A petición se borran su nombre, correo, teléfono, firma y dispositivos. Lo acordado entre dos empresas permanece, porque borrar a una persona no deshace un acuerdo, pero ya sin su nombre.",
    "fr": "Sur demande, vos nom, e-mail, téléphone, signature et appareils sont supprimés. Ce que deux entreprises ont convenu demeure, car supprimer une personne ne défait pas un accord, mais sans votre nom.",
    "pl": "Na żądanie usuwane są imię, e-mail, telefon, podpis i urządzenia. To, co uzgodniły dwie firmy, zostaje, bo usunięcie osoby nie unieważnia uzgodnienia, ale już bez Państwa nazwiska.",
    "uk": "На запит ваші ім'я, пошта, телефон, підпис і пристрої видаляються. Погоджене між двома компаніями лишається, бо видалення людини не скасовує домовленості, але вже без вашого імені.",
    "pt": "A pedido, o seu nome, e-mail, telefone, assinatura e dispositivos são apagados. O que duas empresas acordaram permanece, porque apagar uma pessoa não desfaz um acordo, mas já sem o seu nome."}),
 ],
}

FAQ = {
 "title": {
  "en": "Questions", "bg": "Въпроси", "de": "Fragen", "ro": "Întrebări",
  "el": "Ερωτήσεις", "tr": "Sorular", "it": "Domande", "ru": "Вопросы",
  "es": "Preguntas", "fr": "Questions", "pl": "Pytania", "uk": "Питання",
  "pt": "Perguntas"},
 "lead": {
  "en": "The four asked before anyone signs up.",
  "bg": "Четирите, които се задават преди регистрация.",
  "de": "Die vier, die vor jeder Anmeldung kommen.",
  "ro": "Cele patru puse înainte de înregistrare.",
  "el": "Τα τέσσερα που ρωτούνται πριν από κάθε εγγραφή.",
  "tr": "Kayıttan önce sorulan dört soru.",
  "it": "Le quattro che si pongono prima di registrarsi.",
  "ru": "Четыре, которые задают до регистрации.",
  "es": "Las cuatro que se hacen antes de registrarse.",
  "fr": "Les quatre posées avant toute inscription.",
  "pl": "Cztery zadawane przed rejestracją.",
  "uk": "Чотири, які ставлять перед реєстрацією.",
  "pt": "As quatro feitas antes de qualquer registo."},
 "items": [
  ({"en": "Do my contractors have to pay?", "bg": "Изпълнителите ми плащат ли?",
    "de": "Müssen meine Auftragnehmer zahlen?", "ro": "Executanții mei plătesc?",
    "el": "Πληρώνουν οι ανάδοχοί μου;", "tr": "Yüklenicilerim ödeme yapar mı?",
    "it": "I miei fornitori devono pagare?", "ru": "Мои исполнители платят?",
    "es": "¿Pagan mis proveedores?", "fr": "Mes prestataires doivent-ils payer?",
    "pl": "Czy moi wykonawcy płacą?", "uk": "Чи платять мої виконавці?",
    "pt": "Os meus fornecedores pagam?"},
   {"en": "Only the company that opens the workspace is billed. The companies it invites are not, on any plan.",
    "bg": "Таксува се само фирмата, която открива работното пространство. Поканените от нея не се таксуват при никой план.",
    "de": "Abgerechnet wird nur die Firma, die den Arbeitsbereich eröffnet. Die von ihr eingeladenen Firmen nicht, in keinem Tarif.",
    "ro": "Se facturează numai firma care deschide spațiul de lucru. Firmele invitate de ea nu, la niciun plan.",
    "el": "Χρεώνεται μόνο η εταιρεία που ανοίγει τον χώρο εργασίας. Οι εταιρείες που προσκαλεί δεν χρεώνονται σε κανένα πρόγραμμα.",
    "tr": "Yalnızca çalışma alanını açan şirket faturalandırılır. Onun davet ettiği şirketler hiçbir planda ödemez.",
    "it": "Viene fatturata solo l'azienda che apre lo spazio di lavoro. Quelle che invita no, in nessun piano.",
    "ru": "Счёт выставляется только компании, которая открывает пространство. Приглашённые ею не платят ни на одном плане.",
    "es": "Solo se factura a la empresa que abre el espacio de trabajo. Las que invita no pagan en ningún plan.",
    "fr": "Seule l'entreprise qui ouvre l'espace de travail est facturée. Celles qu'elle invite ne le sont sur aucun forfait.",
    "pl": "Rozliczana jest wyłącznie firma, która otwiera przestrzeń roboczą. Zaproszone przez nią firmy nie płacą w żadnym planie.",
    "uk": "Рахунок отримує лише компанія, яка відкриває простір. Запрошені нею не платять на жодному плані.",
    "pt": "Só é faturada a empresa que abre o espaço de trabalho. As que convida não pagam em nenhum plano."}),

  ({"en": "Can we each work in our own language?",
    "bg": "Може ли всеки да работи на своя език?",
    "de": "Kann jeder in seiner Sprache arbeiten?",
    "ro": "Poate fiecare lucra în limba lui?",
    "el": "Μπορεί ο καθένας να δουλεύει στη γλώσσα του;",
    "tr": "Herkes kendi dilinde çalışabilir mi?",
    "it": "Possiamo lavorare ciascuno nella propria lingua?",
    "ru": "Может ли каждый работать на своём языке?",
    "es": "¿Puede cada uno trabajar en su idioma?",
    "fr": "Chacun peut-il travailler dans sa langue?",
    "pl": "Czy każdy może pracować w swoim języku?",
    "uk": "Чи може кожен працювати своєю мовою?",
    "pt": "Pode cada um trabalhar na sua língua?"},
   {"en": "Yes. The interface is complete in thirteen languages, and a document is written in the language of the person who will read it, not the one who prepared it.",
    "bg": "Да. Интерфейсът е пълен на тринайсет езика, а документът се изготвя на езика на този, който ще го чете, не на този, който го подготвя.",
    "de": "Ja. Die Oberfläche ist in dreizehn Sprachen vollständig, und ein Dokument entsteht in der Sprache dessen, der es liest, nicht dessen, der es erstellt.",
    "ro": "Da. Interfața este completă în treisprezece limbi, iar documentul se redactează în limba celui care îl va citi, nu a celui care îl pregătește.",
    "el": "Ναι. Η διεπαφή είναι πλήρης σε δεκατρείς γλώσσες, και το έγγραφο συντάσσεται στη γλώσσα εκείνου που θα το διαβάσει, όχι εκείνου που το ετοιμάζει.",
    "tr": "Evet. Arayüz on üç dilde eksiksizdir ve belge, hazırlayanın değil okuyacak kişinin dilinde yazılır.",
    "it": "Sì. L'interfaccia è completa in tredici lingue e il documento è scritto nella lingua di chi lo leggerà, non di chi lo prepara.",
    "ru": "Да. Интерфейс полон на тринадцати языках, а документ составляется на языке того, кто будет его читать, а не того, кто его готовит.",
    "es": "Sí. La interfaz está completa en trece idiomas y el documento se redacta en el idioma de quien lo leerá, no de quien lo prepara.",
    "fr": "Oui. L'interface est complète en treize langues, et un document est rédigé dans la langue de celui qui le lira, non de celui qui le prépare.",
    "pl": "Tak. Interfejs jest kompletny w trzynastu językach, a dokument powstaje w języku tego, kto go przeczyta, nie tego, kto go przygotował.",
    "uk": "Так. Інтерфейс повний тринадцятьма мовами, а документ складається мовою того, хто його читатиме, а не того, хто готує.",
    "pt": "Sim. A interface está completa em treze idiomas e o documento é escrito na língua de quem o vai ler, não de quem o prepara."}),

  ({"en": "Does it fit our accounting?", "bg": "Връзва ли се със счетоводството ни?",
    "de": "Passt es zu unserer Buchhaltung?", "ro": "Se potrivește cu contabilitatea noastră?",
    "el": "Ταιριάζει με τη λογιστική μας;", "tr": "Muhasebemize uyar mı?",
    "it": "Si adatta alla nostra contabilità?", "ru": "Подходит ли к нашей бухгалтерии?",
    "es": "¿Encaja con nuestra contabilidad?", "fr": "S'intègre-t-il à notre comptabilité?",
    "pl": "Czy pasuje do naszej księgowości?", "uk": "Чи пасує до нашої бухгалтерії?",
    "pt": "Encaixa na nossa contabilidade?"},
   {"en": "Invoices download as PDF, and bank statements in CAMT.053 or MT940 are read and matched against them, so a payment closes the invoice it belongs to rather than being typed in twice.",
    "bg": "Фактурите се изтеглят като PDF, а банковите извлечения в CAMT.053 или MT940 се четат и съпоставят с тях, тоест плащането затваря своята фактура, вместо да се въвежда два пъти.",
    "de": "Rechnungen laden als PDF, und Kontoauszüge in CAMT.053 oder MT940 werden eingelesen und abgeglichen, sodass eine Zahlung ihre Rechnung schließt, statt zweimal getippt zu werden.",
    "ro": "Facturile se descarcă în PDF, iar extrasele în CAMT.053 sau MT940 se citesc și se potrivesc cu ele, astfel încât o plată închide factura ei, în loc să fie introdusă de două ori.",
    "el": "Τα τιμολόγια κατεβαίνουν σε PDF και τα τραπεζικά αντίγραφα σε CAMT.053 ή MT940 διαβάζονται και αντιστοιχίζονται, ώστε μια πληρωμή να κλείνει το τιμολόγιό της αντί να πληκτρολογείται δύο φορές.",
    "tr": "Faturalar PDF olarak iner; CAMT.053 veya MT940 banka ekstreleri okunur ve eşleştirilir, böylece bir ödeme iki kez girilmek yerine kendi faturasını kapatır.",
    "it": "Le fatture si scaricano in PDF e gli estratti conto in CAMT.053 o MT940 vengono letti e riconciliati, così un pagamento chiude la propria fattura invece di essere digitato due volte.",
    "ru": "Счета скачиваются в PDF, а выписки в CAMT.053 или MT940 читаются и сверяются с ними, так что платёж закрывает свой счёт, а не вводится дважды.",
    "es": "Las facturas se descargan en PDF y los extractos en CAMT.053 o MT940 se leen y concilian, de modo que un cobro cierra su factura en vez de teclearse dos veces.",
    "fr": "Les factures se téléchargent en PDF, et les relevés en CAMT.053 ou MT940 sont lus et rapprochés, si bien qu'un encaissement solde sa facture au lieu d'être saisi deux fois.",
    "pl": "Faktury pobierają się w PDF, a wyciągi w CAMT.053 lub MT940 są wczytywane i uzgadniane, więc wpłata zamyka swoją fakturę zamiast być wpisywana dwa razy.",
    "uk": "Рахунки завантажуються у PDF, а виписки в CAMT.053 або MT940 читаються та звіряються з ними, тож платіж закриває свій рахунок, а не вводиться двічі.",
    "pt": "As faturas descarregam em PDF e os extratos em CAMT.053 ou MT940 são lidos e conciliados, pelo que um recebimento fecha a sua fatura em vez de ser digitado duas vezes."}),

  ({"en": "Can we host it ourselves?", "bg": "Може ли да го държим при нас?",
    "de": "Können wir es selbst betreiben?", "ro": "Îl putem găzdui noi?",
    "el": "Μπορούμε να το φιλοξενήσουμε μόνοι μας;", "tr": "Kendimiz barındırabilir miyiz?",
    "it": "Possiamo ospitarlo noi?", "ru": "Можем ли мы держать его у себя?",
    "es": "¿Podemos alojarlo nosotros?", "fr": "Pouvons-nous l'héberger nous-mêmes?",
    "pl": "Czy możemy hostować to u siebie?", "uk": "Чи можемо тримати його в себе?",
    "pt": "Podemos alojá-lo nós próprios?"},
   {"en": "Yes, and that is the usual case. It runs on one machine with Python and a single SQLite file, and needs no outside service to work.",
    "bg": "Да, и това е обичайното. Работи на една машина с Python и един файл SQLite, без да му трябва външна услуга.",
    "de": "Ja, und das ist der Normalfall. Es läuft auf einer Maschine mit Python und einer einzigen SQLite-Datei und braucht keinen fremden Dienst.",
    "ro": "Da, și acesta este cazul obișnuit. Rulează pe o singură mașină cu Python și un fișier SQLite și nu are nevoie de niciun serviciu extern.",
    "el": "Ναι, και αυτό είναι το σύνηθες. Τρέχει σε ένα μηχάνημα με Python και ένα αρχείο SQLite, χωρίς να χρειάζεται εξωτερική υπηρεσία.",
    "tr": "Evet, olağan olan da budur. Python ve tek bir SQLite dosyasıyla tek makinede çalışır, dışarıdan bir hizmete ihtiyaç duymaz.",
    "it": "Sì, ed è il caso abituale. Gira su una macchina con Python e un solo file SQLite, senza bisogno di servizi esterni.",
    "ru": "Да, и это обычный случай. Работает на одной машине с Python и одним файлом SQLite, без внешних служб.",
    "es": "Sí, y es lo habitual. Funciona en una máquina con Python y un único archivo SQLite, sin necesitar servicios externos.",
    "fr": "Oui, et c'est le cas courant. Il tourne sur une machine avec Python et un seul fichier SQLite, sans service extérieur.",
    "pl": "Tak, i tak zwykle bywa. Działa na jednej maszynie z Pythonem i jednym plikiem SQLite, bez potrzeby usług zewnętrznych.",
    "uk": "Так, і це звичайний випадок. Працює на одній машині з Python і одним файлом SQLite, без зовнішніх служб.",
    "pt": "Sim, e é o caso habitual. Corre numa máquina com Python e um único ficheiro SQLite, sem precisar de serviços externos."}),
 ],
}
